#                                    DataFrame

In [9]:
import pandas as pd
import numpy as np

In [3]:
data= { 
    'Name':   ['Alice', 'Bob', 'Charlie', 'Diana'], 
    'Age':    [25, 30, 35, 28], 
    'Score':  [88.5, 92.0, 79.5, 95.0], 
    'City':   ['Mumbai', 'Delhi', 'Pune', 'Chennai'] 
}

In [4]:
d1 = pd.DataFrame(data)
d1

      Name  Age  Score     City
0    Alice   25   88.5   Mumbai
1      Bob   30   92.0    Delhi
2  Charlie   35   79.5     Pune
3    Diana   28   95.0  Chennai

In [5]:
d1["Name"]

0      Alice
1        Bob
2    Charlie
3      Diana
Name: Name, dtype: str

In [7]:
rows = [{'Name':'Alice','Age':25}, {'Name':'Bob','Age':30}] 
df2 = pd.DataFrame(rows) 
df2

    Name  Age
0  Alice   25
1    Bob   30

In [12]:
arr = np.random.randint(1,100,(4,3))
arr

array([[75, 60, 26],
       [ 8,  5, 71],
       [95, 51, 52],
       [33, 81, 76]], dtype=int32)

In [13]:
df3 = pd.DataFrame(arr, columns=['A','B','C']) 
df3

    A   B   C
0  75  60  26
1   8   5  71
2  95  51  52
3  33  81  76